// This header file was auto-generated by ClassMate++
// Created: 22 Nov 2021 6:51:08 pm
// Copyright (c) 2021, HurleyWorks

#pragma once

struct RayIntersectionInfo
{
    Eigen::Vector3f rayOrigin = Eigen::Vector3f::Zero();
    Eigen::Vector3f rayDirection = Eigen::Vector3f::Zero();
    Eigen::Vector3f rayHitPoint = Eigen::Vector3f::Constant (std::numeric_limits<float>::max());
    Eigen::Vector3f hitSurfaceNormal = Eigen::Vector3f::Zero();
    ItemID hitItem = INVALID_ID;
};