// This header file was auto-generated by ClassMate++
// Created: 11 Apr 2013 8:51:49 am
// Copyright (c) 2013, HurleyWorks

#pragma  once

template <typename T>
class Box3Box3Intersect : public Intersector<T, Eigen::Matrix<T,3,1>  >
		/// TODO: Add a comment about the role
		/// and responsibilty of class Box3Box3Intersect
{

 public:
	Box3Box3Intersect (const Box3<T> & box0, const Box3<T> & box1);
		/// Creates a Box3Box3Intersect instance

	~Box3Box3Intersect ();
		/// Destroys a Box3Box3Intersect instance

	virtual bool test ();
		/// TODO: Add a comment for the test method

 private:
    const Box3<T>* box0_;
    const Box3<T>* box1_;

}; // end class Box3Box3Intersect

typedef Box3Box3Intersect<float> Box3Box3ISectf;
typedef Box3Box3Intersect<double> Box3Box3ISectd;