// This source file was auto-generated by ClassMate++
// Created: 5 Jul 2016 10:58:30 am
// Copyright (c) 2016, HurleyWorks

// ctor
template <typename T, typename vector_t>
Distance<T, vector_t>::Distance ()
{	
}

// dtor
template <typename T, typename vector_t>
Distance<T, vector_t>::~Distance ()
{	
}

