// This header file was auto-generated by ClassMate++
// Created: 5 Jul 2016 10:58:30 am
// Copyright (c) 2016, HurleyWorks

// Geometric Tools, LLC
// Copyright (c) 1998-2014
// Distributed under the Boost Software License, Version 1.0.
// http://www.boost.org/LICENSE_1_0.txt
// http://www.geometrictools.com/License/Boost/LICENSE_1_0.txt
//

#pragma once

template <typename T>
class Line3Seg3Dist : public Distance<T, Eigen::Matrix<T, 3, 1>  >
{

 public:
	Line3Seg3Dist (const Line3D<T>& line, const Segment3<T>& segment);
	~Line3Seg3Dist ();
	
	// Object access.
	const Line3D<T>& GetLine() const { return *mLine; }
	const Segment3<T>& GetSegment() const { return *mSegment; }


	// Static distance queries.
	virtual T Get() { return Math<T>::Sqrt(GetSquared()); }
	virtual T GetSquared();

	// Information about the closest points.
	T GetLineParameter() const { return mLineParameter; }
	T GetSegmentParameter() const { return mSegmentParameter; }

private:
	using Distance<T, Eigen::Matrix<T, 3, 1> >::mClosestPoint0;
	using Distance<T, Eigen::Matrix<T, 3, 1> >::mClosestPoint1;

	const Line3D<T>* mLine;
	const Segment3<T>* mSegment;

	// Information about the closest points.
	T mLineParameter;  // closest0 = line.origin+param*line.direction
	T mSegmentParameter;  // closest1 = seg.origin+param*seg.direction

}; // end class Line3Seg3Dist
