// This header file was auto-generated by ClassMate++
// Created: 6 Mar 2009 9:34:37 pm
// Copyright (c) 2009, HurleyWorks

// Geometric Tools, LLC
// Copyright (c) 1998-2010
// Distributed under the Boost Software License, Version 1.0.
// http://www.boost.org/LICENSE_1_0.txt
// http://www.geometrictools.com/License/Boost/LICENSE_1_0.txt
//
// File Version: 5.0.0 (2010/01/01)

#pragma once

template <typename T>
class Line2
{

 public:
    // The line is represented as P+t*D where P is the line origin, D is a
    // unit-length direction vector, and t is any real number.  The user must
    // ensure that D is indeed unit length.

    // Construction and destruction.
    Line2 ();  // uninitialized
    ~Line2 ();

    Line2 (const Eigen::Matrix<T,2,1>& origin, const Eigen::Matrix<T,2,1>& direction);

    Eigen::Matrix<T,2,1> origin, direction;
};


template <typename T>
Line2<T>::Line2 ()
{
}

template <typename T>
Line2<T>::~Line2 ()
{
}

template <typename T>
Line2<T>::Line2 (const Eigen::Matrix<T,2,1>& origin, const Eigen::Matrix<T,2,1>& direction)
    : origin(origin),
      direction(direction)
{
}
