// This header file was auto-generated by ClassMate++
// Created: 5 Jul 2016 10:58:30 am
// Copyright (c) 2016, HurleyWorks

// Geometric Tools, LLC
// Copyright (c) 1998-2014
// Distributed under the Boost Software License, Version 1.0.
// http://www.boost.org/LICENSE_1_0.txt
// http://www.geometrictools.com/License/Boost/LICENSE_1_0.txt
//

#pragma once

template <typename T>
class Seg3Tri3Dist : public Distance<T, Eigen::Matrix<T, 3, 1>  >
{

 public:
	Seg3Tri3Dist (const Segment3 <T> & segment, const Triangle3 <T> & triangle);
	~Seg3Tri3Dist ();
	
	// Object access.
	const Segment3<T>& GetSegment() const { return *mSegment; }
	const Triangle3<T>& GetTriangle() const { return *mTriangle; }

	// Static distance queries.
	virtual T Get() { return Math<T>::Sqrt(GetSquared()); }
	virtual T GetSquared();

	// Information about the closest points.
	T GetSegmentParameter() const { return mSegmentParameter; }
	T GetTriangleBary(int i) const {return mTriangleBary[i]; }

private:
	using Distance<T, Eigen::Matrix<T, 3, 1> >::mClosestPoint0;
	using Distance<T, Eigen::Matrix<T, 3, 1> >::mClosestPoint1;

	const Segment3<T>* mSegment;
	const Triangle3<T>* mTriangle;

	// Information about the closest points.
	T mSegmentParameter;  // closest0 = seg.origin+param*seg.direction
	T mTriangleBary[3];  // closest1 = sum_{i=0}^2 bary[i]*tri.vertex[i]

}; // end class Seg3Tri3Dist
