// This header file was auto-generated by ClassMate++
// Created: 6 Oct 2009 7:11:54 am
// Copyright (c) 2009, HurleyWorks

#pragma once

template<typename T>
struct Voxel
{

 public:
	typedef std::vector <size_t> VoxelHits;

 public:
	Voxel ();
	~Voxel() = default;
	
	BoundingBox3 <T> bbox;
	VoxelHits hits;
	size_t id;

}; // end class Voxel

template<typename T>
Voxel<T>::Voxel()
	: hits(),
	  bbox()
{	
}


typedef Voxel<float> Voxelf;
typedef Voxel<double> Voxeld;


