// This header file was auto-generated by ClassMate++
// Created: 23 Jan 2018 7:09:22 pm
// Copyright (c) 2018, HurleyWorks

#pragma once

using Eigen::Vector3f;

class NormalizedClump : public LoadStrategy
{

 public:
	NormalizedClump ();
	~NormalizedClump();
		
	void addNextItem(SpaceTime & spacetime) override;
	void reset() override
	{
		objIndex = 1;
	}
    void incrementCount() override
    {
        ++objIndex;
	}
 private:
	int objIndex = 1;

	void computeNextSpot(int index, float density, Vector3f & spot);

}; // end class NormalizedClump
